from ultralytics import YOLO

# This script converts a trained PyTorch model (.pt) into the ONNX format
# for efficient, cross-platform inference.

# --- CONFIGURATION ---
# 1. Point this to the '.pt' file generated by the training process.
#    This is typically found in 'runs/detect/train/weights/best.pt'.
TRAINED_MODEL_PATH = "runs/detect/train/weights/best.pt"

# 2. The output name for your final ONNX model.
ONNX_OUTPUT_PATH = "yolov8s_finetuned.onnx"
# --- END CONFIGURATION ---

print(f"1. Loading trained PyTorch model from: {TRAINED_MODEL_PATH}")
model = YOLO(TRAINED_MODEL_PATH)

print(f"2. Compiling static ONNX graph to: {ONNX_OUTPUT_PATH}")
# Setting a fixed imgsz and explicitly setting dynamic=False is critical for
# maximum compatibility and performance, especially with DirectML.
model.export(format="onnx", imgsz=640, dynamic=False, opset=12)

print(f"\n[SUCCESS] Fine-tuned ONNX model compiled successfully to '{ONNX_OUTPUT_PATH}'!")